repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-illegal-windows-names
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: file-contents-sorter
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
      - id: forbid-new-submodules
      - id: forbid-submodules
      - id: mixed-line-ending
      - id: name-tests-test
      - id: no-commit-to-branch
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        entry: go fmt
        files: \.go$
        language: system
        pass_filenames: false

      - id: prettier-fmt
        name: prettier
        entry: yarn prettier --write .
        files: \.go$
        language: system
        pass_filenames: false

      - id: go-vet
        name: go vet
        entry: go vet
        files: \.go$
        language: system
        pass_filenames: false

      - id: go-imports
        name: goimports
        entry: goimports
        files: \.go$
        language: system

      - id: go-cyclo
        name: gocyclo
        entry: gocyclo -over 15
        files: \.go$
        language: system

      - id: golangci-lint
        name: golangci-lint
        entry: golangci-lint run
        files: \.go$
        language: system
        pass_filenames: false

      - id: go-unit-tests
        name: go test
        entry: go test -v ./...
        files: \.go$
        language: system
        pass_filenames: false

      - id: go-build
        name: go build
        entry: go build -v ./...
        files: \.go$
        language: system
        pass_filenames: false

      - id: go-mod-tidy
        name: go mod tidy
        entry: go mod tidy
        files: go\.mod$
        language: system
        pass_filenames: false

      - id: hadolint
        name: hadolint
        entry: hadolint
        files: ".*Containerfile.*"
        language: system

      - id: shellcheck
        name: shellcheck
        entry: shellcheck
        files: ^.*\.(ba|z|fish|k|mksh|posh|sh)$
        language: system

      - id: markdownlint
        name: markdownlint
        entry: npx markdownlint --config .markdownlint.json
        files: \.md$
        language: node
        types: [markdown]

      - id: podman-build
        name: podman build
        entry: yarn node scripts/tasks/buildContainers.ts all
        files: ^(Containerfile|\.containerignore|\.go-version|.*\.go|go\.mod|go\.sum)$
        language: system
        pass_filenames: false
