# Jekyll configuration
lsi: false
safe: true
source: "./"
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
title: [Bootstrap OLM]
description:
  [
    Bootstrap OLM - A tool to bootstrap the Operator Lifecycle Manager (OLM) in a non-OpenShift cluster.,
  ]
exclude:
  - .github/
  - .mypy_cache/
  - .venv/
  - .vscode/
  - .yarn/
  - charts/
  - internal/
  - node_modules/
  - pkg/
  - scripts/
  - vendor/
  - _config.yml
  - .after.custom.envrc
  - .before.custom.envrc
  - .containerignore
  - .editorconfig
  - .envrc
  - .gitignore
  - .go-version
  - .markdownlint.json
  - .pre-commit-config.yaml
  - .ruby-version
  - Brewfile
  - Containerfile
  - Gemfile
  - Gemfile.lock
  - go.mod
  - go.sum
  - LICENSE
  - Makefile

repository: jacksonporter/bootstrap-olm
author: Jackson Porter (JP)
github: [metadata]
url: "https://bootstrap-olm.jacksonporterjp.com"
# baseurl: "/"bundle exec jekyll serve --baseurl=""
