[default]
# Default container file path
containerfilePath = "{{GIT_PROJECT_ROOT}}/Containerfile"
contextPath = "{{GIT_PROJECT_ROOT}}"
selectedBuildArgs = ["GO_VERSION"]
selectedRepositories = ["ghcr-jacksonporter-bootstrap-olm"]

# Default build args
buildArgs.GO_VERSION.cmd = "mise current go"
buildArgs.GO_VERSION.orderPrecedence = ["cmd"]

# Default tag templates
testingTagTemplates = [
  "testing-{{env.GITHUB_REF_NAME}}-{{CONTAINER_NAME}}-{{PLATFORM}}-{{ARCH}}-{{env.GITHUB_RUN_ID}}-{{env.GITHUB_RUN_NUMBER}}",
]
platformTagTemplates = [
  "{{env.GITHUB_REF_NAME}}-{{CONTAINER_NAME}}-{{PLATFORM}}-{{ARCH}}",
]
manifestTagTemplates = [
  "{{env.GITHUB_REF_NAME}}-{{CONTAINER_NAME}}",
]

# Default CI settings
ci.defaultRunnerLabels = ["ubuntu-latest"]
ci.useBuildkit = false

[repositories.ghcr-jacksonporter-bootstrap-olm]
type = "standard"
registry = "ghcr.io"
repository = "jacksonporter/bootstrap-olm"
username = "{{env.GITHUB_ACTOR}}"
password = "{{env.GITHUB_TOKEN}}"

# ##############################################################################
# Debug container
# ##############################################################################
[containers.debug]
name = "debug"

default.target = "debug"

# Container platforms

# linux/amd64 variant
linuxPlatforms.amd64.platform_slug = "linux/amd64"
linuxPlatforms.amd64.ci.defaultRunnerLabels = [
  "ubuntu-24.04",
] # x86_64 linux runner

# linux/arm64 variant
linuxPlatforms.arm64.platform_slug = "linux/arm64"
linuxPlatforms.arm64.ci.defaultRunnerLabels = [
  "ubuntu-24.04-arm",
] # arm64 linux runner

# linux/ppc64le variant
linuxPlatforms.ppc64le.platform_slug = "linux/ppc64le"
linuxPlatforms.ppc64le.ci.defaultRunnerLabels = [
  "ubuntu-24.04",
] # x86_64 linux runner
linuxPlatforms.ppc64le.ci.useBuildkit = true

# linux/s390x variant
linuxPlatforms.s390x.platform_slug = "linux/s390x"
linuxPlatforms.s390x.ci.defaultRunnerLabels = [
  "ubuntu-24.04",
] # x86_64 linux runner
linuxPlatforms.s390x.ci.useBuildkit = true

# windows/amd64 variant
windowsPlatforms.amd64.arch = "amd64"
windowsPlatforms.amd64.containerfilePath = "{{GIT_PROJECT_ROOT}}/Dockerfile.windows"
windowsPlatforms.amd64.ci.defaultRunnerLabels = [
  "windows-2025",
] # x86_64 windows runner


# ##############################################################################
# "Release" container
# ##############################################################################
[containers.release]
name = "release"

# Default tag templates
default.testingTagTemplates = [
  "{{env.GITHUB_REF_NAME}}-{{PLATFORM}}-{{ARCH}}-{{env.GITHUB_RUN_ID}}-{{env.GITHUB_RUN_NUMBER}}",
]
default.platformTagTemplates = ["{{env.GITHUB_REF_NAME}}-{{PLATFORM}}-{{ARCH}}"]
default.manifestTagTemplates = ["{{env.GITHUB_REF_NAME}}"]

# Container platforms

# linux/amd64 variant
linuxPlatforms.amd64.platform_slug = "linux/amd64"
linuxPlatforms.amd64.ci.defaultRunnerLabels = [
  "ubuntu-24.04",
] # x86_64 linux runner

# linux/arm64 variant
linuxPlatforms.arm64.platform_slug = "linux/arm64"
linuxPlatforms.arm64.ci.defaultRunnerLabels = [
  "ubuntu-24.04-arm",
] # arm64 linux runner

# linux/ppc64le variant
linuxPlatforms.ppc64le.platform_slug = "linux/ppc64le"
linuxPlatforms.ppc64le.ci.defaultRunnerLabels = [
  "ubuntu-24.04",
] # x86_64 linux runner
linuxPlatforms.ppc64le.ci.useBuildkit = true

# linux/s390x variant
linuxPlatforms.s390x.platform_slug = "linux/s390x"
linuxPlatforms.s390x.ci.defaultRunnerLabels = [
  "ubuntu-24.04",
] # x86_64 linux runner
linuxPlatforms.s390x.ci.useBuildkit = true

# windows/amd64 variant
windowsPlatforms.amd64.arch = "amd64"
windowsPlatforms.amd64.containerfilePath = "{{GIT_PROJECT_ROOT}}/Dockerfile.windows"
windowsPlatforms.amd64.ci.defaultRunnerLabels = [
  "windows-2025",
] # x86_64 windows runner
