[debug]
type = "debug"
repository = "ghcr.io/jacksonporter/bootstrap-olm"
tag = "debug"
target = "debug"
add_arch_before_manifest = true
prepend_tag_with_version = true
containerfile = "Containerfile"

[[debug.platforms]]
os = "linux"
arch = "amd64"

[[debug.platforms]]
os = "linux"
arch = "arm64"

[[debug.platforms]]
os = "windows"
arch = "amd64"

[[debug.platforms]]
os = "windows"
arch = "arm64"

[production]
type = "production"
repository = "ghcr.io/jacksonporter/bootstrap-olm"
tag = ""
add_arch_before_manifest = true
prepend_tag_with_version = true
containerfile = "Containerfile"
