name: Audit

on:
  pull_request:
  push:

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - name: Update apt cache
        run: |
          sudo apt-get update

      - name: Checkout code
        uses: actions/checkout@v4

      - id: get-python-version
        name: Get Python version
        run: echo "PYTHON_VERSION=$(cat .python-version)" >> $GITHUB_OUTPUT

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ steps.get-python-version.outputs.PYTHON_VERSION }}

      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: .go-version
          cache: true

      - name: Install Go dependencies
        run: go mod download

      - name: Install hadolint
        run: |
          curl -sSfL https://github.com/hadolint/hadolint/releases/latest/download/hadolint-$(uname -s)-$(uname -m) -o hadolint
          chmod +x hadolint
          sudo mv hadolint /usr/local/bin/

      - name: Install shellcheck
        run: sudo apt-get install -y shellcheck

      - name: Install go tools
        run: |
          while IFS= read -r tool; do
            [ -n "$tool" ] && go install "$tool"
          done <gotools.txt

      - uses: pre-commit/action@v3.0.1
        env:
          SKIP: podman-build
      - uses: pre-commit-ci/lite-action@v1.1.0
        if: always()
