name: Audit

on:
  pull_request:
  push:

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: jdx/mise-action@v2
        with:
          experimental: true # [default: false] enable experimental features

      - name: Update apt cache
        run: |
          sudo apt-get update

      - name: Install hadolint
        run: |
          curl -sSfL https://github.com/hadolint/hadolint/releases/latest/download/hadolint-$(uname -s)-$(uname -m) -o hadolint
          chmod +x hadolint
          sudo mv hadolint /usr/local/bin/

      - name: Install shellcheck
        run: sudo apt-get install -y shellcheck

      - name: Install project dependencies
        run: mise run 'install'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1

      - name: audit
        env:
          SKIP: podman-build,golangci-lint
        run: mise run 'audit'

      - uses: pre-commit-ci/lite-action@v1.1.0
        if: always()
